### ISSUE TITLE
mobile first design

### ISSUE THREAD

**Issue by cnell-usgs** [USGS-VIZLAB/what-is-drought#11]
current layout needs to be reviewed for mobile-friendliness. both views should be super similar, using a sticky chart with scrolling boxes that roll over.

**Comment by aaarcher-usgs** [comment]
Design mocked up in XD, Mobile and Tablet to have a text box overlaying the page at the bottom with changing text and primary graphics built in the middle. Still to decide whether text should also scroll on laptop/desktop websites or stay "stuck" like on mobile. 

![image](https://user-images.githubusercontent.com/19958841/195928506-b880f8e3-dd34-49b3-b15c-8d4b4c11079a.png)
