### ISSUE TITLE
Transparent images need fade mechanic on website

### ISSUE THREAD

**Issue by aaarcher-usgs** [USGS-VIZLAB/what-is-drought#13]
The current set up with the assets that overlap on top of each other in the scrolly website will have to be updated because of the new transparent background:

![image](https://user-images.githubusercontent.com/19958841/181796468-568de23c-406a-4502-bd6b-a69591b982cf.png)

**Comment by cnell-usgs** [comment]
This was resolved with https://github.com/USGS-VIZLAB/what-is-drought/pull/17
