### ISSUE TITLE
Before release, update meta card urls

### ISSUE THREAD

**Issue by hcorson-dosch-usgs** [USGS-VIZLAB/what-is-drought#58]
Currently point to beta for testing (#55 , #57 ), should be repointed to prod before release

**Comment by aaarcher-usgs** [comment]
@hcorson-dosch-usgs  - can this be closed?

**Comment by hcorson-dosch-usgs** [comment]
Not yet - it's still pointing to beta [here](https://github.com/USGS-VIZLAB/what-is-drought/blob/main/public/index.html#L43), so that I could test it. Now that I know the meta cards are working, I can make this update
