### ISSUE TITLE
visualizing drought properties through time

### ISSUE THREAD

**Issue by cnell-usgs** [USGS-VIZLAB/what-is-drought#7]
Some notes as I explore the drought properties. The novelty of these data are that they quantify drought duration, mean and max intensity, severity, and deficit for 5 thresholds from 1950-2020 nationally. 

Sites in drought with fixed threshold, across the 5 threshold categories: 
![image](https://user-images.githubusercontent.com/17803537/180885828-51c87b95-c05e-4694-b3a7-64d8205003c9.png)

By region: 
![image](https://user-images.githubusercontent.com/17803537/180907843-9cc33bf5-e3b0-4c2e-9526-b0030fff6c57.png)

Looks like the number of sites in NE is driving main pattern visible at national level. Using opacity mapped to sites:
![image](https://user-images.githubusercontent.com/17803537/180910283-72152013-e93a-47b2-96af-e5b8e8dc19bb.png)

**Comment by cnell-usgs** [comment]
Plotting the number of sites in each threshold through time 
![image](https://user-images.githubusercontent.com/17803537/180888114-704cc9e8-9531-426b-8fbf-b416700e3817.png)


 By region: 
 
![image](https://user-images.githubusercontent.com/17803537/180911918-74aa9f8b-226f-451d-9447-d0f65f9ed0d9.png)

**Comment by aaarcher-usgs** [comment]
This issue is now being addressed through a separate viz and repo looking at the history of drought.
