### ISSUE TITLE
export frames into assets

### ISSUE THREAD

**Issue by cnell-usgs** [USGS-VIZLAB/what-is-drought#9]
Need to adapt pipeline so that frames coming from the R pipeline are exported into the `src/assets/` folder where they are picked up by vue.

**Comment by aaarcher-usgs** [comment]
I rolled this change into my learner viz design branch. Marking complete.

**Comment by cnell-usgs** [comment]
If you write closes https://github.com/USGS-VIZLAB/what-is-drought/issues/9 on your PR, it will close this once merged

https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

**Comment by aaarcher-usgs** [comment]
Good to know!!!
